/* eslint-disable no-unused-vars */
/* eslint-disable no-constant-condition */


/**
 * Adjust the expected response for autogenerated values, acts as a pseudomock
 * @param   {Object}    expected        The default expected response.
 * @param   {Object}    received        The response given in an execution.
 * @return  {Object}                    The expected value modified according to the response.
 */
const responseHandler = (expected, received) => {
    if (expected.data) {
        expected = expected.data;
    }
    Object.keys(expected).forEach(variableData => {
        if (expected[variableData] !== null) {
            if (expected[variableData].toString().includes('auto-generated')) {
                let kindOfVariable = expected[variableData].replace('auto-generated-', '');
                if ((kindOfVariable = typeof received[variableData])) {
                    expected[variableData] = received[variableData];
                }
            }
        }
    });
    return expected;
};

module.exports = { responseHandler };