name: "Component testing"
on: 
    workflow_dispatch:
        inputs:
          microservice:
            description: Microservicio a probar
            required: true
jobs:

    init:
        runs-on: ubuntu-latest
        steps:
            - name: start repository
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
            - name: Setup images
              run: |
                    ls
                    docker image build -t component_test:1.0 .  	
                    docker run   --detach -p 3001:3001 component_test:1.0 
                    docker exec -it component_test:1.0  bash -c "cd /opt/app/testing_components_v1/ && node index.js"
              env:
                DATA: ${{ github.event.inputs.microservice }}

            - name: Upload artefacts
              uses: actions/upload-artifact@v2
              with:
                name: response
                paths: /testing_components_v1/component_test/artefact/**
            - name: Download a single artifact
              uses: actions/download-artifact@v2
              with: 
                name: response