name: "Component testing"
on: 
    workflow_dispatch:
        inputs:
          microservice:
            description: Microservicio a probar
            required: true
jobs:

    init:
        runs-on: ubuntu-latest
        steps:
            - name: start repository
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
            - name: Setup images
              run: |

                    cd component_test 
                    npm install
                    node index.js
              env:
                DATA: ${{ github.event.inputs.microservice }}

            - name: Upload artefacts
              uses: actions/upload-artifact@v2
              with:
                name: response
                path: /component_test/artefact/
            - name: Download a single artifact
              uses: actions/download-artifact@v2
              with: 
                name: response