name: "Component testing"

jobs:
    inputs:
        microservice:
            description: Microservice name
            required: true

    init:
        runs-on: ubuntu-latest
        steps:
            - name: start repository
              uses: action/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
            - name: Setup images
              run: |
                    cd testing_components_v1 
                    cd component_test && docker image build -t component_test:1.0 .  	
                    docker run   --detach -p 3001:3001 --network=mesfix --name mesfix-test --rm component_test:1.0 
                    docker exec -it  mesfix-test bash -c "cd /opt/app/testing_components_v1/component_test
                    npm install && cd /opt/app/testing_components_v1/api && node index.js"
            - name: init 
              run: |
                    cd testing_components_v1 && cd component_test && node index.js
              env:
                DATA: ${{ inputs.microservice }}

            - name: Upload artefacts
              uses: actions/upload-artifact@v2
              with:
                name: response
                paths: /testing_components_v1/component_test/artefact/**
            - name: Download a single artifact
              uses: actions/download-artifact@v2
              with: 
                name: response